### ISSUE TITLE
GH Pages

### ISSUE THREAD

**Issue by IonicaBizau** [alexarnautu/html5-snake#1]
It would be cool to create the `gh-pages` branch and it will already be working. 😁 

In the meantime I played it here: https://rawgit.com/alexarnautu/html5-snake/master/index.html

Nice work! 👍

**Comment by alexarnautu** [comment]
Thanks a lot! :smiley: I didn't know about this feature. Now you can play it here [http://alexarnautu.github.io/html5-snake](http://alexarnautu.github.io/html5-snake/)

**Comment by IonicaBizau** [comment]
Great 😀
